package se.poroli.fhirplace.r5.structuremap;

import se.poroli.fhirplace.r5.valuesets.CodedEnum;

/**
 * If field is a list, how to manage the production.
 *
 * @see <a href="http://hl7.org/fhir/ValueSet/map-target-list-mode">FHIR R5 StructureMapTargetListMode</a>
 */
public enum StructureMapTargetListMode implements CodedEnum {

    /** when the target list is being assembled, the items for this rule go first. */
    FIRST("first", "First"),

    /**
     * the target instance is shared with the target instances generated by another rule (up to the first common n
     * items, then create new ones).
     */
    SHARE("share", "Share"),

    /** when the target list is being assembled, the items for this rule go last. */
    LAST("last", "Last"),

    /**
     * the target instance is shared with a number of target instances generated by another rule (up to the first
     * common n items, then create new ones).
     */
    SINGLE("single", "single");

    private final String code;
    private final String display;

    StructureMapTargetListMode(String code, String display) {
        this.code = code;
        this.display = display;
    }

    @Override
    public String system() {
        return "http://hl7.org/fhir/map-target-list-mode";
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String display() {
        return display;
    }

    /**
     * Returns the constant for a code.
     *
     * @param code the code, which is case-sensitive
     * @return the constant
     * @throws IllegalArgumentException if the code system does not define the code
     */
    public static StructureMapTargetListMode fromCode(String code) {
        for (StructureMapTargetListMode value : values()) {
            if (value.code.equals(code)) {
                return value;
            }
        }
        throw new IllegalArgumentException("Unknown StructureMapTargetListMode code: '" + code + "'");
    }
}
