package se.poroli.fhirplace.r5.valuesets;

/**
 * The type of relationship to the related artifact.
 *
 * @see <a href="http://hl7.org/fhir/ValueSet/related-artifact-type">FHIR R5 RelatedArtifactType</a>
 */
public enum RelatedArtifactType implements CodedEnum {

    /** Additional documentation for the knowledge resource. */
    DOCUMENTATION("documentation", "Documentation"),

    /**
     * The target artifact is a summary of the justification for the knowledge resource including supporting evidence,
     * relevant guidelines, or other clinically important information.
     */
    JUSTIFICATION("justification", "Justification"),

    /** Bibliographic citation for papers, references, or other relevant material for the knowledge resource. */
    CITATION("citation", "Citation"),

    /**
     * The previous version of the knowledge artifact, used to establish an ordering of versions of an artifact,
     * independent of the status of each version.
     */
    PREDECESSOR("predecessor", "Predecessor"),

    /**
     * The subsequent version of the knowledge artfact, used to establish an ordering of versions of an artifact,
     * independent of the status of each version.
     */
    SUCCESSOR("successor", "Successor"),

    /** This artifact is derived from the target artifact. */
    DERIVED_FROM("derived-from", "Derived From"),

    /** This artifact depends on the target artifact. */
    DEPENDS_ON("depends-on", "Depends On"),

    /** This artifact is composed of the target artifact. */
    COMPOSED_OF("composed-of", "Composed Of"),

    /** This artifact is a part of the target artifact. */
    PART_OF("part-of", "Part Of"),

    /** This artifact amends or changes the target artifact. */
    AMENDS("amends", "Amends"),

    /** This artifact is amended with or changed by the target artifact. */
    AMENDED_WITH("amended-with", "Amended With"),

    /** This artifact adds additional information to the target artifact. */
    APPENDS("appends", "Appends"),

    /** This artifact has additional information in the target artifact. */
    APPENDED_WITH("appended-with", "Appended With"),

    /** This artifact cites the target artifact. */
    CITES("cites", "Cites"),

    /** This artifact is cited by the target artifact. */
    CITED_BY("cited-by", "Cited By"),

    /** This artifact contains comments about the target artifact. */
    COMMENTS_ON("comments-on", "Is Comment On"),

    /** This artifact has comments about it in the target artifact. */
    COMMENT_IN("comment-in", "Has Comment In"),

    /** This artifact is a container in which the target artifact is contained. */
    CONTAINS("contains", "Contains"),

    /** This artifact is contained in the target artifact. */
    CONTAINED_IN("contained-in", "Contained In"),

    /** This artifact identifies errors and replacement content for the target artifact. */
    CORRECTS("corrects", "Corrects"),

    /** This artifact has corrections to it in the target artifact. */
    CORRECTION_IN("correction-in", "Correction In"),

    /** This artifact replaces or supersedes the target artifact. */
    REPLACES("replaces", "Replaces"),

    /** This artifact is replaced with or superseded by the target artifact. */
    REPLACED_WITH("replaced-with", "Replaced With"),

    /** This artifact retracts the target artifact. */
    RETRACTS("retracts", "Retracts"),

    /** This artifact is retracted by the target artifact. */
    RETRACTED_BY("retracted-by", "Retracted By"),

    /** This artifact is a signature of the target artifact. */
    SIGNS("signs", "Signs"),

    /** This artifact has characteristics in common with the target artifact. */
    SIMILAR_TO("similar-to", "Similar To"),

    /** This artifact provides additional support for the target artifact. */
    SUPPORTS("supports", "Supports"),

    /**
     * The target artifact contains additional information related to the knowledge artifact but is not documentation
     * as the additional information does not describe, explain, or instruct regarding the knowledge artifact content
     * or application.
     */
    SUPPORTED_WITH("supported-with", "Supported With"),

    /** This artifact was generated by transforming the target artifact (e.g., format or language conversion). */
    TRANSFORMS("transforms", "Transforms"),

    /** This artifact was transformed into the target artifact (e.g., by format or language conversion). */
    TRANSFORMED_INTO("transformed-into", "Transformed Into"),

    /**
     * This artifact was generated by transforming a related artifact (e.g., format or language conversion), noted
     * separately with the “transforms” relationship type.
     */
    TRANSFORMED_WITH("transformed-with", "Transformed With"),

    /** This artifact provides additional documentation for the target artifact. */
    DOCUMENTS("documents", "Documents"),

    /** The target artifact is a precise description of a concept in this artifact. */
    SPECIFICATION_OF("specification-of", "Specification Of"),

    /** This artifact was created with the target artifact. */
    CREATED_WITH("created-with", "Created With"),

    /** The related artifact is the citation for this artifact. */
    CITE_AS("cite-as", "Cite As");

    private final String code;
    private final String display;

    RelatedArtifactType(String code, String display) {
        this.code = code;
        this.display = display;
    }

    @Override
    public String system() {
        return "http://hl7.org/fhir/related-artifact-type";
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String display() {
        return display;
    }

    /**
     * Returns the constant for a code.
     *
     * @param code the code, which is case-sensitive
     * @return the constant
     * @throws IllegalArgumentException if the code system does not define the code
     */
    public static RelatedArtifactType fromCode(String code) {
        for (RelatedArtifactType value : values()) {
            if (value.code.equals(code)) {
                return value;
            }
        }
        throw new IllegalArgumentException("Unknown RelatedArtifactType code: '" + code + "'");
    }
}
