package se.poroli.fhirplace.r5.valuesets;

/**
 * The type of relationship between reports.
 *
 * @see <a href="http://hl7.org/fhir/ValueSet/report-relation-type">FHIR R5 ReportRelationshipType</a>
 */
public enum ReportRelationshipType implements CodedEnum {

    /** This document replaces or supersedes the target document. */
    REPLACES("replaces", "Replaces"),

    /** This document notes corrections or changes to replace or supersede parts of the target document. */
    AMENDS("amends", "Amends"),

    /** This document adds additional information to the target document. */
    APPENDS("appends", "Appends"),

    /** This document was generated by transforming the target document (eg format or language conversion). */
    TRANSFORMS("transforms", "Transforms"),

    /** This document was. */
    REPLACED_WITH("replacedWith", "Replaced With"),

    /** This document was. */
    AMENDED_WITH("amendedWith", "Amended With"),

    /** This document was. */
    APPENDED_WITH("appendedWith", "Appended With"),

    /** This document was. */
    TRANSFORMED_WITH("transformedWith", "Transformed With");

    private final String code;
    private final String display;

    ReportRelationshipType(String code, String display) {
        this.code = code;
        this.display = display;
    }

    @Override
    public String system() {
        return "http://hl7.org/fhir/report-relation-type";
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String display() {
        return display;
    }

    /**
     * Returns the constant for a code.
     *
     * @param code the code, which is case-sensitive
     * @return the constant
     * @throws IllegalArgumentException if the code system does not define the code
     */
    public static ReportRelationshipType fromCode(String code) {
        for (ReportRelationshipType value : values()) {
            if (value.code.equals(code)) {
                return value;
            }
        }
        throw new IllegalArgumentException("Unknown ReportRelationshipType code: '" + code + "'");
    }
}
