package se.poroli.fhirplace.r5.implementationguide;

import se.poroli.fhirplace.r5.valuesets.CodedEnum;

/**
 * A code that indicates how the page is generated.
 *
 * @see <a href="http://hl7.org/fhir/ValueSet/guide-page-generation">FHIR R5 GuidePageGeneration</a>
 */
public enum GuidePageGeneration implements CodedEnum {

    /** Page is proper xhtml with no templating. */
    HTML("html", "HTML"),

    /** Page is markdown with templating. */
    MARKDOWN("markdown", "Markdown"),

    /** Page is xml with templating. */
    XML("xml", "XML"),

    /** Page will be generated by the publication process - no source to bring across. */
    GENERATED("generated", "Generated");

    private final String code;
    private final String display;

    GuidePageGeneration(String code, String display) {
        this.code = code;
        this.display = display;
    }

    @Override
    public String system() {
        return "http://hl7.org/fhir/guide-page-generation";
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String display() {
        return display;
    }

    /**
     * Returns the constant for a code.
     *
     * @param code the code, which is case-sensitive
     * @return the constant
     * @throws IllegalArgumentException if the code system does not define the code
     */
    public static GuidePageGeneration fromCode(String code) {
        for (GuidePageGeneration value : values()) {
            if (value.code.equals(code)) {
                return value;
            }
        }
        throw new IllegalArgumentException("Unknown GuidePageGeneration code: '" + code + "'");
    }
}
