package se.poroli.fhirplace.r5.bundle;

import se.poroli.fhirplace.r5.valuesets.CodedEnum;

/**
 * Indicates the purpose of a bundle - how it is intended to be used.
 *
 * @see <a href="http://hl7.org/fhir/ValueSet/bundle-type">FHIR R5 BundleType</a>
 */
public enum BundleType implements CodedEnum {

    /** The bundle is a document. */
    DOCUMENT("document", "Document"),

    /** The bundle is a message. */
    MESSAGE("message", "Message"),

    /** The bundle is a transaction - intended to be processed by a server as an atomic commit. */
    TRANSACTION("transaction", "Transaction"),

    /** The bundle is a transaction response. */
    TRANSACTION_RESPONSE("transaction-response", "Transaction Response"),

    /** The bundle is a set of actions - intended to be processed by a server as a group of independent actions. */
    BATCH("batch", "Batch"),

    /** The bundle is a batch response. */
    BATCH_RESPONSE("batch-response", "Batch Response"),

    /** The bundle is a list of resources from a history interaction on a server. */
    HISTORY("history", "History List"),

    /**
     * The bundle is a list of resources returned as a result of a search/query interaction, operation, or message.
     */
    SEARCHSET("searchset", "Search Results"),

    /**
     * The bundle is a set of resources collected into a single package for ease of distribution that imposes no
     * processing obligations or behavioral rules beyond persistence.
     */
    COLLECTION("collection", "Collection"),

    /** The bundle has been generated by a Subscription to communicate information to a client. */
    SUBSCRIPTION_NOTIFICATION("subscription-notification", "Subscription Notification");

    private final String code;
    private final String display;

    BundleType(String code, String display) {
        this.code = code;
        this.display = display;
    }

    @Override
    public String system() {
        return "http://hl7.org/fhir/bundle-type";
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String display() {
        return display;
    }

    /**
     * Returns the constant for a code.
     *
     * @param code the code, which is case-sensitive
     * @return the constant
     * @throws IllegalArgumentException if the code system does not define the code
     */
    public static BundleType fromCode(String code) {
        for (BundleType value : values()) {
            if (value.code.equals(code)) {
                return value;
            }
        }
        throw new IllegalArgumentException("Unknown BundleType code: '" + code + "'");
    }
}
