package se.poroli.fhirplace.r5.subscriptiontopic;

import java.time.temporal.Temporal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import se.poroli.fhirplace.r5.DomainResource;
import se.poroli.fhirplace.r5.Resource;
import se.poroli.fhirplace.r5.datatypes.BackboneElement;
import se.poroli.fhirplace.r5.datatypes.CodeableConcept;
import se.poroli.fhirplace.r5.datatypes.Coding;
import se.poroli.fhirplace.r5.datatypes.ContactDetail;
import se.poroli.fhirplace.r5.datatypes.DataType;
import se.poroli.fhirplace.r5.datatypes.Extension;
import se.poroli.fhirplace.r5.datatypes.FhirBoolean;
import se.poroli.fhirplace.r5.datatypes.FhirCanonical;
import se.poroli.fhirplace.r5.datatypes.FhirCode;
import se.poroli.fhirplace.r5.datatypes.FhirDate;
import se.poroli.fhirplace.r5.datatypes.FhirDateTime;
import se.poroli.fhirplace.r5.datatypes.FhirEnum;
import se.poroli.fhirplace.r5.datatypes.FhirMarkdown;
import se.poroli.fhirplace.r5.datatypes.FhirString;
import se.poroli.fhirplace.r5.datatypes.FhirUri;
import se.poroli.fhirplace.r5.datatypes.Identifier;
import se.poroli.fhirplace.r5.datatypes.Meta;
import se.poroli.fhirplace.r5.datatypes.Narrative;
import se.poroli.fhirplace.r5.datatypes.Period;
import se.poroli.fhirplace.r5.datatypes.UsageContext;
import se.poroli.fhirplace.r5.valuesets.PublicationStatus;
import se.poroli.fhirplace.r5.valuesets.SearchComparator;
import se.poroli.fhirplace.r5.valuesets.SearchModifierCode;

/**
 * Describes a stream of resource state changes identified by trigger criteria and annotated with labels useful to
 * filter projections from this topic.
 *
 * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances are
 * usually created with {@link #builder()}.
 *
 * @param id Logical id of this artifact.
 * @param meta Metadata about the resource.
 * @param implicitRules A set of rules under which this content was created. Modifier element.
 * @param language Language of the resource content.
 * @param text Text summary of the resource, for human interpretation.
 * @param contained Contained, inline Resources.
 * @param extension Additional content defined by implementations.
 * @param modifierExtension Extensions that cannot be ignored. Modifier element.
 * @param url Canonical identifier for this subscription topic, represented as an absolute URI (globally unique).
 *   Required.
 * @param identifier Business identifier for subscription topic.
 * @param version Business version of the subscription topic.
 * @param versionAlgorithm How to compare versions. One of string, Coding.
 * @param name Name for this subscription topic (computer friendly).
 * @param title Name for this subscription topic (human friendly).
 * @param derivedFrom Based on FHIR protocol or definition. Canonical reference to SubscriptionTopic.
 * @param status draft | active | retired | unknown. Required. Modifier element.
 * @param experimental If for testing purposes, not real usage.
 * @param date Date status first applied.
 * @param publisher The name of the individual or organization that published the SubscriptionTopic.
 * @param contact Contact details for the publisher.
 * @param description Natural language description of the SubscriptionTopic.
 * @param useContext Content intends to support these contexts.
 * @param jurisdiction Intended jurisdiction of the SubscriptionTopic (if applicable).
 * @param purpose Why this SubscriptionTopic is defined.
 * @param copyright Use and/or publishing restrictions.
 * @param copyrightLabel Copyright holder and year(s).
 * @param approvalDate When SubscriptionTopic is/was approved by publisher.
 * @param lastReviewDate Date the Subscription Topic was last reviewed by the publisher.
 * @param effectivePeriod The effective date range for the SubscriptionTopic.
 * @param resourceTrigger Definition of a resource-based trigger for the subscription topic.
 * @param eventTrigger Event definitions the SubscriptionTopic.
 * @param canFilterBy Properties by which a Subscription can filter notifications from the SubscriptionTopic.
 * @param notificationShape Properties for describing the shape of notifications generated by this topic.
 * @see <a href="http://hl7.org/fhir/StructureDefinition/SubscriptionTopic">FHIR R5 SubscriptionTopic</a>
 */
public record SubscriptionTopic(
        String id,
        Meta meta,
        FhirUri implicitRules,
        FhirCode language,
        Narrative text,
        List<Resource> contained,
        List<Extension> extension,
        List<Extension> modifierExtension,
        FhirUri url,
        List<Identifier> identifier,
        FhirString version,
        DataType versionAlgorithm,
        FhirString name,
        FhirString title,
        List<FhirCanonical> derivedFrom,
        FhirEnum<PublicationStatus> status,
        FhirBoolean experimental,
        FhirDateTime date,
        FhirString publisher,
        List<ContactDetail> contact,
        FhirMarkdown description,
        List<UsageContext> useContext,
        List<CodeableConcept> jurisdiction,
        FhirMarkdown purpose,
        FhirMarkdown copyright,
        FhirString copyrightLabel,
        FhirDate approvalDate,
        FhirDate lastReviewDate,
        Period effectivePeriod,
        List<ResourceTrigger> resourceTrigger,
        List<EventTrigger> eventTrigger,
        List<CanFilterBy> canFilterBy,
        List<NotificationShape> notificationShape) implements DomainResource {

    /**
     * Creates a {@code SubscriptionTopic}, copying all lists.
     *
     * @throws NullPointerException if a required element is absent or a list contains {@code null}
     * @throws IllegalArgumentException if a choice element has a type that is not allowed
     */
    public SubscriptionTopic {
        contained = contained == null ? List.of() : List.copyOf(contained);
        extension = extension == null ? List.of() : List.copyOf(extension);
        modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
        identifier = identifier == null ? List.of() : List.copyOf(identifier);
        derivedFrom = derivedFrom == null ? List.of() : List.copyOf(derivedFrom);
        contact = contact == null ? List.of() : List.copyOf(contact);
        useContext = useContext == null ? List.of() : List.copyOf(useContext);
        jurisdiction = jurisdiction == null ? List.of() : List.copyOf(jurisdiction);
        resourceTrigger = resourceTrigger == null ? List.of() : List.copyOf(resourceTrigger);
        eventTrigger = eventTrigger == null ? List.of() : List.copyOf(eventTrigger);
        canFilterBy = canFilterBy == null ? List.of() : List.copyOf(canFilterBy);
        notificationShape = notificationShape == null ? List.of() : List.copyOf(notificationShape);
        Objects.requireNonNull(url, "SubscriptionTopic.url is required");
        Objects.requireNonNull(status, "SubscriptionTopic.status is required");
        if (versionAlgorithm != null && !(versionAlgorithm instanceof FhirString
                || versionAlgorithm instanceof Coding)) {
            throw new IllegalArgumentException(
                    "SubscriptionTopic.versionAlgorithm[x] must be one of string, Coding, but was "
                            + versionAlgorithm.getClass().getSimpleName());
        }
    }

    /**
     * Returns a new, empty builder.
     *
     * @return the builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Returns a builder initialized with the values of this {@code SubscriptionTopic}.
     *
     * @return the builder
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    /**
     * A definition of a resource-based event that triggers a notification based on the SubscriptionTopic.
     *
     * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances are
     * usually created with {@link #builder()}.
     *
     * @param id Unique id for inter-element referencing.
     * @param extension Additional content defined by implementations.
     * @param modifierExtension Extensions that cannot be ignored even if unrecognized. Modifier element.
     * @param description Text representation of the resource trigger.
     * @param resource Data Type or Resource (reference to definition) for this trigger definition. Required.
     * @param supportedInteraction create | update | delete.
     * @param queryCriteria Query based trigger rule.
     * @param fhirPathCriteria FHIRPath based trigger rule.
     */
    public record ResourceTrigger(
            String id,
            List<Extension> extension,
            List<Extension> modifierExtension,
            FhirMarkdown description,
            FhirUri resource,
            List<FhirEnum<InteractionTrigger>> supportedInteraction,
            QueryCriteria queryCriteria,
            FhirString fhirPathCriteria) implements BackboneElement {

        /**
         * Creates a {@code ResourceTrigger}, copying all lists.
         *
         * @throws NullPointerException if a required element is absent or a list contains {@code null}
         */
        public ResourceTrigger {
            extension = extension == null ? List.of() : List.copyOf(extension);
            modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
            supportedInteraction = supportedInteraction == null ? List.of() : List.copyOf(supportedInteraction);
            Objects.requireNonNull(resource, "SubscriptionTopic.resourceTrigger.resource is required");
        }

        /**
         * Returns a new, empty builder.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * Returns a builder initialized with the values of this {@code ResourceTrigger}.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /**
         * The FHIR query based rules that the server should use to determine when to trigger a notification for this
         * subscription topic.
         *
         * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances
         * are usually created with {@link #builder()}.
         *
         * @param id Unique id for inter-element referencing.
         * @param extension Additional content defined by implementations.
         * @param modifierExtension Extensions that cannot be ignored even if unrecognized. Modifier element.
         * @param previous Rule applied to previous resource state.
         * @param resultForCreate test-passes | test-fails.
         * @param current Rule applied to current resource state.
         * @param resultForDelete test-passes | test-fails.
         * @param requireBoth Both must be true flag.
         */
        public record QueryCriteria(
                String id,
                List<Extension> extension,
                List<Extension> modifierExtension,
                FhirString previous,
                FhirEnum<CriteriaNotExistsBehavior> resultForCreate,
                FhirString current,
                FhirEnum<CriteriaNotExistsBehavior> resultForDelete,
                FhirBoolean requireBoth) implements BackboneElement {

            /**
             * Creates a {@code QueryCriteria}, copying all lists.
             *
             * @throws NullPointerException if a list contains {@code null}
             */
            public QueryCriteria {
                extension = extension == null ? List.of() : List.copyOf(extension);
                modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
            }

            /**
             * Returns a new, empty builder.
             *
             * @return the builder
             */
            public static Builder builder() {
                return new Builder();
            }

            /**
             * Returns a builder initialized with the values of this {@code QueryCriteria}.
             *
             * @return the builder
             */
            public Builder toBuilder() {
                return new Builder(this);
            }

            /** Builder for {@link QueryCriteria}. Builders are mutable and not thread-safe. */
            public static final class Builder {

                private String id;
                private List<Extension> extension = new ArrayList<>();
                private List<Extension> modifierExtension = new ArrayList<>();
                private FhirString previous;
                private FhirEnum<CriteriaNotExistsBehavior> resultForCreate;
                private FhirString current;
                private FhirEnum<CriteriaNotExistsBehavior> resultForDelete;
                private FhirBoolean requireBoth;

                private Builder() {
                }

                private Builder(QueryCriteria original) {
                    this.id = original.id();
                    this.extension = new ArrayList<>(original.extension());
                    this.modifierExtension = new ArrayList<>(original.modifierExtension());
                    this.previous = original.previous();
                    this.resultForCreate = original.resultForCreate();
                    this.current = original.current();
                    this.resultForDelete = original.resultForDelete();
                    this.requireBoth = original.requireBoth();
                }

                /**
                 * Sets {@code id}.
                 *
                 * @param id the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder id(String id) {
                    this.id = id;
                    return this;
                }

                /**
                 * Replaces all {@code extension} values.
                 *
                 * @param extension the new values, or {@code null} to clear them
                 * @return this builder
                 */
                public Builder extension(List<Extension> extension) {
                    this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
                    return this;
                }

                /**
                 * Adds a {@code extension} value.
                 *
                 * @param extension the value to add
                 * @return this builder
                 */
                public Builder addExtension(Extension extension) {
                    this.extension.add(Objects.requireNonNull(extension, "extension"));
                    return this;
                }

                /**
                 * Replaces all {@code modifierExtension} values.
                 *
                 * @param modifierExtension the new values, or {@code null} to clear them
                 * @return this builder
                 */
                public Builder modifierExtension(List<Extension> modifierExtension) {
                    this.modifierExtension = modifierExtension == null
                            ? new ArrayList<>()
                            : new ArrayList<>(modifierExtension);
                    return this;
                }

                /**
                 * Adds a {@code modifierExtension} value.
                 *
                 * @param modifierExtension the value to add
                 * @return this builder
                 */
                public Builder addModifierExtension(Extension modifierExtension) {
                    this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
                    return this;
                }

                /**
                 * Sets {@code previous}.
                 *
                 * @param previous the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder previous(FhirString previous) {
                    this.previous = previous;
                    return this;
                }

                /**
                 * Sets {@code previous}, wrapped in a {@link FhirString} without id or extensions.
                 *
                 * @param previous the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder previous(String previous) {
                    return previous(previous == null ? null : FhirString.of(previous));
                }

                /**
                 * Sets {@code resultForCreate}.
                 *
                 * @param resultForCreate the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder resultForCreate(FhirEnum<CriteriaNotExistsBehavior> resultForCreate) {
                    this.resultForCreate = resultForCreate;
                    return this;
                }

                /**
                 * Sets {@code resultForCreate}, wrapped in a {@link FhirEnum} without id or extensions.
                 *
                 * @param resultForCreate the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder resultForCreate(CriteriaNotExistsBehavior resultForCreate) {
                    return resultForCreate(resultForCreate == null ? null : FhirEnum.of(resultForCreate));
                }

                /**
                 * Sets {@code current}.
                 *
                 * @param current the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder current(FhirString current) {
                    this.current = current;
                    return this;
                }

                /**
                 * Sets {@code current}, wrapped in a {@link FhirString} without id or extensions.
                 *
                 * @param current the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder current(String current) {
                    return current(current == null ? null : FhirString.of(current));
                }

                /**
                 * Sets {@code resultForDelete}.
                 *
                 * @param resultForDelete the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder resultForDelete(FhirEnum<CriteriaNotExistsBehavior> resultForDelete) {
                    this.resultForDelete = resultForDelete;
                    return this;
                }

                /**
                 * Sets {@code resultForDelete}, wrapped in a {@link FhirEnum} without id or extensions.
                 *
                 * @param resultForDelete the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder resultForDelete(CriteriaNotExistsBehavior resultForDelete) {
                    return resultForDelete(resultForDelete == null ? null : FhirEnum.of(resultForDelete));
                }

                /**
                 * Sets {@code requireBoth}.
                 *
                 * @param requireBoth the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder requireBoth(FhirBoolean requireBoth) {
                    this.requireBoth = requireBoth;
                    return this;
                }

                /**
                 * Sets {@code requireBoth}, wrapped in a {@link FhirBoolean} without id or extensions.
                 *
                 * @param requireBoth the value, or {@code null} to clear it
                 * @return this builder
                 */
                public Builder requireBoth(Boolean requireBoth) {
                    return requireBoth(requireBoth == null ? null : FhirBoolean.of(requireBoth));
                }

                /**
                 * Builds the {@code QueryCriteria}.
                 *
                 * @return the {@code QueryCriteria}
                 */
                public QueryCriteria build() {
                    return new QueryCriteria(
                            id, extension, modifierExtension, previous, resultForCreate, current, resultForDelete,
                            requireBoth);
                }
            }
        }

        /** Builder for {@link ResourceTrigger}. Builders are mutable and not thread-safe. */
        public static final class Builder {

            private String id;
            private List<Extension> extension = new ArrayList<>();
            private List<Extension> modifierExtension = new ArrayList<>();
            private FhirMarkdown description;
            private FhirUri resource;
            private List<FhirEnum<InteractionTrigger>> supportedInteraction = new ArrayList<>();
            private QueryCriteria queryCriteria;
            private FhirString fhirPathCriteria;

            private Builder() {
            }

            private Builder(ResourceTrigger original) {
                this.id = original.id();
                this.extension = new ArrayList<>(original.extension());
                this.modifierExtension = new ArrayList<>(original.modifierExtension());
                this.description = original.description();
                this.resource = original.resource();
                this.supportedInteraction = new ArrayList<>(original.supportedInteraction());
                this.queryCriteria = original.queryCriteria();
                this.fhirPathCriteria = original.fhirPathCriteria();
            }

            /**
             * Sets {@code id}.
             *
             * @param id the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder id(String id) {
                this.id = id;
                return this;
            }

            /**
             * Replaces all {@code extension} values.
             *
             * @param extension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder extension(List<Extension> extension) {
                this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
                return this;
            }

            /**
             * Adds a {@code extension} value.
             *
             * @param extension the value to add
             * @return this builder
             */
            public Builder addExtension(Extension extension) {
                this.extension.add(Objects.requireNonNull(extension, "extension"));
                return this;
            }

            /**
             * Replaces all {@code modifierExtension} values.
             *
             * @param modifierExtension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder modifierExtension(List<Extension> modifierExtension) {
                this.modifierExtension = modifierExtension == null
                        ? new ArrayList<>()
                        : new ArrayList<>(modifierExtension);
                return this;
            }

            /**
             * Adds a {@code modifierExtension} value.
             *
             * @param modifierExtension the value to add
             * @return this builder
             */
            public Builder addModifierExtension(Extension modifierExtension) {
                this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
                return this;
            }

            /**
             * Sets {@code description}.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(FhirMarkdown description) {
                this.description = description;
                return this;
            }

            /**
             * Sets {@code description}, wrapped in a {@link FhirMarkdown} without id or extensions.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(String description) {
                return description(description == null ? null : FhirMarkdown.of(description));
            }

            /**
             * Sets {@code resource}.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(FhirUri resource) {
                this.resource = resource;
                return this;
            }

            /**
             * Sets {@code resource}, wrapped in a {@link FhirUri} without id or extensions.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(String resource) {
                return resource(resource == null ? null : FhirUri.of(resource));
            }

            /**
             * Replaces all {@code supportedInteraction} values.
             *
             * @param supportedInteraction the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder supportedInteraction(List<FhirEnum<InteractionTrigger>> supportedInteraction) {
                this.supportedInteraction = supportedInteraction == null
                        ? new ArrayList<>()
                        : new ArrayList<>(supportedInteraction);
                return this;
            }

            /**
             * Adds a {@code supportedInteraction} value.
             *
             * @param supportedInteraction the value to add
             * @return this builder
             */
            public Builder addSupportedInteraction(FhirEnum<InteractionTrigger> supportedInteraction) {
                this.supportedInteraction.add(Objects.requireNonNull(supportedInteraction, "supportedInteraction"));
                return this;
            }

            /**
             * Adds a {@code supportedInteraction} value, wrapped in a {@link FhirEnum} without id or extensions.
             *
             * @param supportedInteraction the value to add
             * @return this builder
             */
            public Builder addSupportedInteraction(InteractionTrigger supportedInteraction) {
                return addSupportedInteraction(FhirEnum.of(supportedInteraction));
            }

            /**
             * Sets {@code queryCriteria}.
             *
             * @param queryCriteria the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder queryCriteria(QueryCriteria queryCriteria) {
                this.queryCriteria = queryCriteria;
                return this;
            }

            /**
             * Sets {@code fhirPathCriteria}.
             *
             * @param fhirPathCriteria the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder fhirPathCriteria(FhirString fhirPathCriteria) {
                this.fhirPathCriteria = fhirPathCriteria;
                return this;
            }

            /**
             * Sets {@code fhirPathCriteria}, wrapped in a {@link FhirString} without id or extensions.
             *
             * @param fhirPathCriteria the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder fhirPathCriteria(String fhirPathCriteria) {
                return fhirPathCriteria(fhirPathCriteria == null ? null : FhirString.of(fhirPathCriteria));
            }

            /**
             * Builds the {@code ResourceTrigger}.
             *
             * @return the {@code ResourceTrigger}
             * @throws NullPointerException if a required element is absent
             */
            public ResourceTrigger build() {
                return new ResourceTrigger(
                        id, extension, modifierExtension, description, resource, supportedInteraction, queryCriteria,
                        fhirPathCriteria);
            }
        }
    }

    /**
     * Event definition which can be used to trigger the SubscriptionTopic.
     *
     * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances are
     * usually created with {@link #builder()}.
     *
     * @param id Unique id for inter-element referencing.
     * @param extension Additional content defined by implementations.
     * @param modifierExtension Extensions that cannot be ignored even if unrecognized. Modifier element.
     * @param description Text representation of the event trigger.
     * @param event Event which can trigger a notification from the SubscriptionTopic. Required.
     * @param resource Data Type or Resource (reference to definition) for this trigger definition. Required.
     */
    public record EventTrigger(
            String id,
            List<Extension> extension,
            List<Extension> modifierExtension,
            FhirMarkdown description,
            CodeableConcept event,
            FhirUri resource) implements BackboneElement {

        /**
         * Creates an {@code EventTrigger}, copying all lists.
         *
         * @throws NullPointerException if a required element is absent or a list contains {@code null}
         */
        public EventTrigger {
            extension = extension == null ? List.of() : List.copyOf(extension);
            modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
            Objects.requireNonNull(event, "SubscriptionTopic.eventTrigger.event is required");
            Objects.requireNonNull(resource, "SubscriptionTopic.eventTrigger.resource is required");
        }

        /**
         * Returns a new, empty builder.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * Returns a builder initialized with the values of this {@code EventTrigger}.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /** Builder for {@link EventTrigger}. Builders are mutable and not thread-safe. */
        public static final class Builder {

            private String id;
            private List<Extension> extension = new ArrayList<>();
            private List<Extension> modifierExtension = new ArrayList<>();
            private FhirMarkdown description;
            private CodeableConcept event;
            private FhirUri resource;

            private Builder() {
            }

            private Builder(EventTrigger original) {
                this.id = original.id();
                this.extension = new ArrayList<>(original.extension());
                this.modifierExtension = new ArrayList<>(original.modifierExtension());
                this.description = original.description();
                this.event = original.event();
                this.resource = original.resource();
            }

            /**
             * Sets {@code id}.
             *
             * @param id the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder id(String id) {
                this.id = id;
                return this;
            }

            /**
             * Replaces all {@code extension} values.
             *
             * @param extension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder extension(List<Extension> extension) {
                this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
                return this;
            }

            /**
             * Adds a {@code extension} value.
             *
             * @param extension the value to add
             * @return this builder
             */
            public Builder addExtension(Extension extension) {
                this.extension.add(Objects.requireNonNull(extension, "extension"));
                return this;
            }

            /**
             * Replaces all {@code modifierExtension} values.
             *
             * @param modifierExtension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder modifierExtension(List<Extension> modifierExtension) {
                this.modifierExtension = modifierExtension == null
                        ? new ArrayList<>()
                        : new ArrayList<>(modifierExtension);
                return this;
            }

            /**
             * Adds a {@code modifierExtension} value.
             *
             * @param modifierExtension the value to add
             * @return this builder
             */
            public Builder addModifierExtension(Extension modifierExtension) {
                this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
                return this;
            }

            /**
             * Sets {@code description}.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(FhirMarkdown description) {
                this.description = description;
                return this;
            }

            /**
             * Sets {@code description}, wrapped in a {@link FhirMarkdown} without id or extensions.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(String description) {
                return description(description == null ? null : FhirMarkdown.of(description));
            }

            /**
             * Sets {@code event}.
             *
             * @param event the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder event(CodeableConcept event) {
                this.event = event;
                return this;
            }

            /**
             * Sets {@code resource}.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(FhirUri resource) {
                this.resource = resource;
                return this;
            }

            /**
             * Sets {@code resource}, wrapped in a {@link FhirUri} without id or extensions.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(String resource) {
                return resource(resource == null ? null : FhirUri.of(resource));
            }

            /**
             * Builds the {@code EventTrigger}.
             *
             * @return the {@code EventTrigger}
             * @throws NullPointerException if a required element is absent
             */
            public EventTrigger build() {
                return new EventTrigger(
                        id, extension, modifierExtension, description, event, resource);
            }
        }
    }

    /**
     * List of properties by which Subscriptions on the SubscriptionTopic can be filtered.
     *
     * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances are
     * usually created with {@link #builder()}.
     *
     * @param id Unique id for inter-element referencing.
     * @param extension Additional content defined by implementations.
     * @param modifierExtension Extensions that cannot be ignored even if unrecognized. Modifier element.
     * @param description Description of this filter parameter.
     * @param resource URL of the triggering Resource that this filter applies to.
     * @param filterParameter Human-readable and computation-friendly name for a filter parameter usable by
     *   subscriptions on this topic, via Subscription.filterBy.filterParameter. Required.
     * @param filterDefinition Canonical URL for a filterParameter definition.
     * @param comparator eq | ne | gt | lt | ge | le | sa | eb | ap.
     * @param modifier missing | exact | contains | not | text | in | not-in | below | above | type | identifier |
     *   of-type | code-text | text-advanced | iterate.
     */
    public record CanFilterBy(
            String id,
            List<Extension> extension,
            List<Extension> modifierExtension,
            FhirMarkdown description,
            FhirUri resource,
            FhirString filterParameter,
            FhirUri filterDefinition,
            List<FhirEnum<SearchComparator>> comparator,
            List<FhirEnum<SearchModifierCode>> modifier) implements BackboneElement {

        /**
         * Creates a {@code CanFilterBy}, copying all lists.
         *
         * @throws NullPointerException if a required element is absent or a list contains {@code null}
         */
        public CanFilterBy {
            extension = extension == null ? List.of() : List.copyOf(extension);
            modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
            comparator = comparator == null ? List.of() : List.copyOf(comparator);
            modifier = modifier == null ? List.of() : List.copyOf(modifier);
            Objects.requireNonNull(filterParameter, "SubscriptionTopic.canFilterBy.filterParameter is required");
        }

        /**
         * Returns a new, empty builder.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * Returns a builder initialized with the values of this {@code CanFilterBy}.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /** Builder for {@link CanFilterBy}. Builders are mutable and not thread-safe. */
        public static final class Builder {

            private String id;
            private List<Extension> extension = new ArrayList<>();
            private List<Extension> modifierExtension = new ArrayList<>();
            private FhirMarkdown description;
            private FhirUri resource;
            private FhirString filterParameter;
            private FhirUri filterDefinition;
            private List<FhirEnum<SearchComparator>> comparator = new ArrayList<>();
            private List<FhirEnum<SearchModifierCode>> modifier = new ArrayList<>();

            private Builder() {
            }

            private Builder(CanFilterBy original) {
                this.id = original.id();
                this.extension = new ArrayList<>(original.extension());
                this.modifierExtension = new ArrayList<>(original.modifierExtension());
                this.description = original.description();
                this.resource = original.resource();
                this.filterParameter = original.filterParameter();
                this.filterDefinition = original.filterDefinition();
                this.comparator = new ArrayList<>(original.comparator());
                this.modifier = new ArrayList<>(original.modifier());
            }

            /**
             * Sets {@code id}.
             *
             * @param id the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder id(String id) {
                this.id = id;
                return this;
            }

            /**
             * Replaces all {@code extension} values.
             *
             * @param extension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder extension(List<Extension> extension) {
                this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
                return this;
            }

            /**
             * Adds a {@code extension} value.
             *
             * @param extension the value to add
             * @return this builder
             */
            public Builder addExtension(Extension extension) {
                this.extension.add(Objects.requireNonNull(extension, "extension"));
                return this;
            }

            /**
             * Replaces all {@code modifierExtension} values.
             *
             * @param modifierExtension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder modifierExtension(List<Extension> modifierExtension) {
                this.modifierExtension = modifierExtension == null
                        ? new ArrayList<>()
                        : new ArrayList<>(modifierExtension);
                return this;
            }

            /**
             * Adds a {@code modifierExtension} value.
             *
             * @param modifierExtension the value to add
             * @return this builder
             */
            public Builder addModifierExtension(Extension modifierExtension) {
                this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
                return this;
            }

            /**
             * Sets {@code description}.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(FhirMarkdown description) {
                this.description = description;
                return this;
            }

            /**
             * Sets {@code description}, wrapped in a {@link FhirMarkdown} without id or extensions.
             *
             * @param description the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder description(String description) {
                return description(description == null ? null : FhirMarkdown.of(description));
            }

            /**
             * Sets {@code resource}.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(FhirUri resource) {
                this.resource = resource;
                return this;
            }

            /**
             * Sets {@code resource}, wrapped in a {@link FhirUri} without id or extensions.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(String resource) {
                return resource(resource == null ? null : FhirUri.of(resource));
            }

            /**
             * Sets {@code filterParameter}.
             *
             * @param filterParameter the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder filterParameter(FhirString filterParameter) {
                this.filterParameter = filterParameter;
                return this;
            }

            /**
             * Sets {@code filterParameter}, wrapped in a {@link FhirString} without id or extensions.
             *
             * @param filterParameter the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder filterParameter(String filterParameter) {
                return filterParameter(filterParameter == null ? null : FhirString.of(filterParameter));
            }

            /**
             * Sets {@code filterDefinition}.
             *
             * @param filterDefinition the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder filterDefinition(FhirUri filterDefinition) {
                this.filterDefinition = filterDefinition;
                return this;
            }

            /**
             * Sets {@code filterDefinition}, wrapped in a {@link FhirUri} without id or extensions.
             *
             * @param filterDefinition the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder filterDefinition(String filterDefinition) {
                return filterDefinition(filterDefinition == null ? null : FhirUri.of(filterDefinition));
            }

            /**
             * Replaces all {@code comparator} values.
             *
             * @param comparator the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder comparator(List<FhirEnum<SearchComparator>> comparator) {
                this.comparator = comparator == null ? new ArrayList<>() : new ArrayList<>(comparator);
                return this;
            }

            /**
             * Adds a {@code comparator} value.
             *
             * @param comparator the value to add
             * @return this builder
             */
            public Builder addComparator(FhirEnum<SearchComparator> comparator) {
                this.comparator.add(Objects.requireNonNull(comparator, "comparator"));
                return this;
            }

            /**
             * Adds a {@code comparator} value, wrapped in a {@link FhirEnum} without id or extensions.
             *
             * @param comparator the value to add
             * @return this builder
             */
            public Builder addComparator(SearchComparator comparator) {
                return addComparator(FhirEnum.of(comparator));
            }

            /**
             * Replaces all {@code modifier} values.
             *
             * @param modifier the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder modifier(List<FhirEnum<SearchModifierCode>> modifier) {
                this.modifier = modifier == null ? new ArrayList<>() : new ArrayList<>(modifier);
                return this;
            }

            /**
             * Adds a {@code modifier} value.
             *
             * @param modifier the value to add
             * @return this builder
             */
            public Builder addModifier(FhirEnum<SearchModifierCode> modifier) {
                this.modifier.add(Objects.requireNonNull(modifier, "modifier"));
                return this;
            }

            /**
             * Adds a {@code modifier} value, wrapped in a {@link FhirEnum} without id or extensions.
             *
             * @param modifier the value to add
             * @return this builder
             */
            public Builder addModifier(SearchModifierCode modifier) {
                return addModifier(FhirEnum.of(modifier));
            }

            /**
             * Builds the {@code CanFilterBy}.
             *
             * @return the {@code CanFilterBy}
             * @throws NullPointerException if a required element is absent
             */
            public CanFilterBy build() {
                return new CanFilterBy(
                        id, extension, modifierExtension, description, resource, filterParameter, filterDefinition,
                        comparator, modifier);
            }
        }
    }

    /**
     * List of properties to describe the shape (e.g., resources) included in notifications from this Subscription
     * Topic.
     *
     * <p>Absent single-valued elements are {@code null} and absent repeating elements are empty lists. Instances are
     * usually created with {@link #builder()}.
     *
     * @param id Unique id for inter-element referencing.
     * @param extension Additional content defined by implementations.
     * @param modifierExtension Extensions that cannot be ignored even if unrecognized. Modifier element.
     * @param resource URL of the Resource that is the focus (main) resource in a notification shape. Required.
     * @param include Include directives, rooted in the resource for this shape.
     * @param revInclude Reverse include directives, rooted in the resource for this shape.
     */
    public record NotificationShape(
            String id,
            List<Extension> extension,
            List<Extension> modifierExtension,
            FhirUri resource,
            List<FhirString> include,
            List<FhirString> revInclude) implements BackboneElement {

        /**
         * Creates a {@code NotificationShape}, copying all lists.
         *
         * @throws NullPointerException if a required element is absent or a list contains {@code null}
         */
        public NotificationShape {
            extension = extension == null ? List.of() : List.copyOf(extension);
            modifierExtension = modifierExtension == null ? List.of() : List.copyOf(modifierExtension);
            include = include == null ? List.of() : List.copyOf(include);
            revInclude = revInclude == null ? List.of() : List.copyOf(revInclude);
            Objects.requireNonNull(resource, "SubscriptionTopic.notificationShape.resource is required");
        }

        /**
         * Returns a new, empty builder.
         *
         * @return the builder
         */
        public static Builder builder() {
            return new Builder();
        }

        /**
         * Returns a builder initialized with the values of this {@code NotificationShape}.
         *
         * @return the builder
         */
        public Builder toBuilder() {
            return new Builder(this);
        }

        /** Builder for {@link NotificationShape}. Builders are mutable and not thread-safe. */
        public static final class Builder {

            private String id;
            private List<Extension> extension = new ArrayList<>();
            private List<Extension> modifierExtension = new ArrayList<>();
            private FhirUri resource;
            private List<FhirString> include = new ArrayList<>();
            private List<FhirString> revInclude = new ArrayList<>();

            private Builder() {
            }

            private Builder(NotificationShape original) {
                this.id = original.id();
                this.extension = new ArrayList<>(original.extension());
                this.modifierExtension = new ArrayList<>(original.modifierExtension());
                this.resource = original.resource();
                this.include = new ArrayList<>(original.include());
                this.revInclude = new ArrayList<>(original.revInclude());
            }

            /**
             * Sets {@code id}.
             *
             * @param id the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder id(String id) {
                this.id = id;
                return this;
            }

            /**
             * Replaces all {@code extension} values.
             *
             * @param extension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder extension(List<Extension> extension) {
                this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
                return this;
            }

            /**
             * Adds a {@code extension} value.
             *
             * @param extension the value to add
             * @return this builder
             */
            public Builder addExtension(Extension extension) {
                this.extension.add(Objects.requireNonNull(extension, "extension"));
                return this;
            }

            /**
             * Replaces all {@code modifierExtension} values.
             *
             * @param modifierExtension the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder modifierExtension(List<Extension> modifierExtension) {
                this.modifierExtension = modifierExtension == null
                        ? new ArrayList<>()
                        : new ArrayList<>(modifierExtension);
                return this;
            }

            /**
             * Adds a {@code modifierExtension} value.
             *
             * @param modifierExtension the value to add
             * @return this builder
             */
            public Builder addModifierExtension(Extension modifierExtension) {
                this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
                return this;
            }

            /**
             * Sets {@code resource}.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(FhirUri resource) {
                this.resource = resource;
                return this;
            }

            /**
             * Sets {@code resource}, wrapped in a {@link FhirUri} without id or extensions.
             *
             * @param resource the value, or {@code null} to clear it
             * @return this builder
             */
            public Builder resource(String resource) {
                return resource(resource == null ? null : FhirUri.of(resource));
            }

            /**
             * Replaces all {@code include} values.
             *
             * @param include the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder include(List<FhirString> include) {
                this.include = include == null ? new ArrayList<>() : new ArrayList<>(include);
                return this;
            }

            /**
             * Adds a {@code include} value.
             *
             * @param include the value to add
             * @return this builder
             */
            public Builder addInclude(FhirString include) {
                this.include.add(Objects.requireNonNull(include, "include"));
                return this;
            }

            /**
             * Adds a {@code include} value, wrapped in a {@link FhirString} without id or extensions.
             *
             * @param include the value to add
             * @return this builder
             */
            public Builder addInclude(String include) {
                return addInclude(FhirString.of(include));
            }

            /**
             * Replaces all {@code revInclude} values.
             *
             * @param revInclude the new values, or {@code null} to clear them
             * @return this builder
             */
            public Builder revInclude(List<FhirString> revInclude) {
                this.revInclude = revInclude == null ? new ArrayList<>() : new ArrayList<>(revInclude);
                return this;
            }

            /**
             * Adds a {@code revInclude} value.
             *
             * @param revInclude the value to add
             * @return this builder
             */
            public Builder addRevInclude(FhirString revInclude) {
                this.revInclude.add(Objects.requireNonNull(revInclude, "revInclude"));
                return this;
            }

            /**
             * Adds a {@code revInclude} value, wrapped in a {@link FhirString} without id or extensions.
             *
             * @param revInclude the value to add
             * @return this builder
             */
            public Builder addRevInclude(String revInclude) {
                return addRevInclude(FhirString.of(revInclude));
            }

            /**
             * Builds the {@code NotificationShape}.
             *
             * @return the {@code NotificationShape}
             * @throws NullPointerException if a required element is absent
             */
            public NotificationShape build() {
                return new NotificationShape(
                        id, extension, modifierExtension, resource, include, revInclude);
            }
        }
    }

    /** Builder for {@link SubscriptionTopic}. Builders are mutable and not thread-safe. */
    public static final class Builder {

        private String id;
        private Meta meta;
        private FhirUri implicitRules;
        private FhirCode language;
        private Narrative text;
        private List<Resource> contained = new ArrayList<>();
        private List<Extension> extension = new ArrayList<>();
        private List<Extension> modifierExtension = new ArrayList<>();
        private FhirUri url;
        private List<Identifier> identifier = new ArrayList<>();
        private FhirString version;
        private DataType versionAlgorithm;
        private FhirString name;
        private FhirString title;
        private List<FhirCanonical> derivedFrom = new ArrayList<>();
        private FhirEnum<PublicationStatus> status;
        private FhirBoolean experimental;
        private FhirDateTime date;
        private FhirString publisher;
        private List<ContactDetail> contact = new ArrayList<>();
        private FhirMarkdown description;
        private List<UsageContext> useContext = new ArrayList<>();
        private List<CodeableConcept> jurisdiction = new ArrayList<>();
        private FhirMarkdown purpose;
        private FhirMarkdown copyright;
        private FhirString copyrightLabel;
        private FhirDate approvalDate;
        private FhirDate lastReviewDate;
        private Period effectivePeriod;
        private List<ResourceTrigger> resourceTrigger = new ArrayList<>();
        private List<EventTrigger> eventTrigger = new ArrayList<>();
        private List<CanFilterBy> canFilterBy = new ArrayList<>();
        private List<NotificationShape> notificationShape = new ArrayList<>();

        private Builder() {
        }

        private Builder(SubscriptionTopic original) {
            this.id = original.id();
            this.meta = original.meta();
            this.implicitRules = original.implicitRules();
            this.language = original.language();
            this.text = original.text();
            this.contained = new ArrayList<>(original.contained());
            this.extension = new ArrayList<>(original.extension());
            this.modifierExtension = new ArrayList<>(original.modifierExtension());
            this.url = original.url();
            this.identifier = new ArrayList<>(original.identifier());
            this.version = original.version();
            this.versionAlgorithm = original.versionAlgorithm();
            this.name = original.name();
            this.title = original.title();
            this.derivedFrom = new ArrayList<>(original.derivedFrom());
            this.status = original.status();
            this.experimental = original.experimental();
            this.date = original.date();
            this.publisher = original.publisher();
            this.contact = new ArrayList<>(original.contact());
            this.description = original.description();
            this.useContext = new ArrayList<>(original.useContext());
            this.jurisdiction = new ArrayList<>(original.jurisdiction());
            this.purpose = original.purpose();
            this.copyright = original.copyright();
            this.copyrightLabel = original.copyrightLabel();
            this.approvalDate = original.approvalDate();
            this.lastReviewDate = original.lastReviewDate();
            this.effectivePeriod = original.effectivePeriod();
            this.resourceTrigger = new ArrayList<>(original.resourceTrigger());
            this.eventTrigger = new ArrayList<>(original.eventTrigger());
            this.canFilterBy = new ArrayList<>(original.canFilterBy());
            this.notificationShape = new ArrayList<>(original.notificationShape());
        }

        /**
         * Sets {@code id}.
         *
         * @param id the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Sets {@code meta}.
         *
         * @param meta the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder meta(Meta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Sets {@code implicitRules}.
         *
         * @param implicitRules the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder implicitRules(FhirUri implicitRules) {
            this.implicitRules = implicitRules;
            return this;
        }

        /**
         * Sets {@code implicitRules}, wrapped in a {@link FhirUri} without id or extensions.
         *
         * @param implicitRules the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder implicitRules(String implicitRules) {
            return implicitRules(implicitRules == null ? null : FhirUri.of(implicitRules));
        }

        /**
         * Sets {@code language}.
         *
         * @param language the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder language(FhirCode language) {
            this.language = language;
            return this;
        }

        /**
         * Sets {@code language}, wrapped in a {@link FhirCode} without id or extensions.
         *
         * @param language the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder language(String language) {
            return language(language == null ? null : FhirCode.of(language));
        }

        /**
         * Sets {@code text}.
         *
         * @param text the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder text(Narrative text) {
            this.text = text;
            return this;
        }

        /**
         * Replaces all {@code contained} values.
         *
         * @param contained the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder contained(List<Resource> contained) {
            this.contained = contained == null ? new ArrayList<>() : new ArrayList<>(contained);
            return this;
        }

        /**
         * Adds a {@code contained} value.
         *
         * @param contained the value to add
         * @return this builder
         */
        public Builder addContained(Resource contained) {
            this.contained.add(Objects.requireNonNull(contained, "contained"));
            return this;
        }

        /**
         * Replaces all {@code extension} values.
         *
         * @param extension the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder extension(List<Extension> extension) {
            this.extension = extension == null ? new ArrayList<>() : new ArrayList<>(extension);
            return this;
        }

        /**
         * Adds a {@code extension} value.
         *
         * @param extension the value to add
         * @return this builder
         */
        public Builder addExtension(Extension extension) {
            this.extension.add(Objects.requireNonNull(extension, "extension"));
            return this;
        }

        /**
         * Replaces all {@code modifierExtension} values.
         *
         * @param modifierExtension the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder modifierExtension(List<Extension> modifierExtension) {
            this.modifierExtension = modifierExtension == null
                    ? new ArrayList<>()
                    : new ArrayList<>(modifierExtension);
            return this;
        }

        /**
         * Adds a {@code modifierExtension} value.
         *
         * @param modifierExtension the value to add
         * @return this builder
         */
        public Builder addModifierExtension(Extension modifierExtension) {
            this.modifierExtension.add(Objects.requireNonNull(modifierExtension, "modifierExtension"));
            return this;
        }

        /**
         * Sets {@code url}.
         *
         * @param url the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder url(FhirUri url) {
            this.url = url;
            return this;
        }

        /**
         * Sets {@code url}, wrapped in a {@link FhirUri} without id or extensions.
         *
         * @param url the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder url(String url) {
            return url(url == null ? null : FhirUri.of(url));
        }

        /**
         * Replaces all {@code identifier} values.
         *
         * @param identifier the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder identifier(List<Identifier> identifier) {
            this.identifier = identifier == null ? new ArrayList<>() : new ArrayList<>(identifier);
            return this;
        }

        /**
         * Adds a {@code identifier} value.
         *
         * @param identifier the value to add
         * @return this builder
         */
        public Builder addIdentifier(Identifier identifier) {
            this.identifier.add(Objects.requireNonNull(identifier, "identifier"));
            return this;
        }

        /**
         * Sets {@code version}.
         *
         * @param version the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder version(FhirString version) {
            this.version = version;
            return this;
        }

        /**
         * Sets {@code version}, wrapped in a {@link FhirString} without id or extensions.
         *
         * @param version the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder version(String version) {
            return version(version == null ? null : FhirString.of(version));
        }

        /**
         * Sets {@code versionAlgorithm} to a string.
         *
         * @param versionAlgorithm the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder versionAlgorithm(FhirString versionAlgorithm) {
            this.versionAlgorithm = versionAlgorithm;
            return this;
        }

        /**
         * Sets {@code versionAlgorithm} to a Coding.
         *
         * @param versionAlgorithm the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder versionAlgorithm(Coding versionAlgorithm) {
            this.versionAlgorithm = versionAlgorithm;
            return this;
        }

        /**
         * Sets {@code versionAlgorithm} to a string without id or extensions.
         *
         * @param versionAlgorithm the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder versionAlgorithm(String versionAlgorithm) {
            this.versionAlgorithm = versionAlgorithm == null ? null : FhirString.of(versionAlgorithm);
            return this;
        }

        /**
         * Sets {@code name}.
         *
         * @param name the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder name(FhirString name) {
            this.name = name;
            return this;
        }

        /**
         * Sets {@code name}, wrapped in a {@link FhirString} without id or extensions.
         *
         * @param name the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder name(String name) {
            return name(name == null ? null : FhirString.of(name));
        }

        /**
         * Sets {@code title}.
         *
         * @param title the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder title(FhirString title) {
            this.title = title;
            return this;
        }

        /**
         * Sets {@code title}, wrapped in a {@link FhirString} without id or extensions.
         *
         * @param title the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder title(String title) {
            return title(title == null ? null : FhirString.of(title));
        }

        /**
         * Replaces all {@code derivedFrom} values.
         *
         * @param derivedFrom the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder derivedFrom(List<FhirCanonical> derivedFrom) {
            this.derivedFrom = derivedFrom == null ? new ArrayList<>() : new ArrayList<>(derivedFrom);
            return this;
        }

        /**
         * Adds a {@code derivedFrom} value.
         *
         * @param derivedFrom the value to add
         * @return this builder
         */
        public Builder addDerivedFrom(FhirCanonical derivedFrom) {
            this.derivedFrom.add(Objects.requireNonNull(derivedFrom, "derivedFrom"));
            return this;
        }

        /**
         * Adds a {@code derivedFrom} value, wrapped in a {@link FhirCanonical} without id or extensions.
         *
         * @param derivedFrom the value to add
         * @return this builder
         */
        public Builder addDerivedFrom(String derivedFrom) {
            return addDerivedFrom(FhirCanonical.of(derivedFrom));
        }

        /**
         * Sets {@code status}.
         *
         * @param status the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder status(FhirEnum<PublicationStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * Sets {@code status}, wrapped in a {@link FhirEnum} without id or extensions.
         *
         * @param status the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder status(PublicationStatus status) {
            return status(status == null ? null : FhirEnum.of(status));
        }

        /**
         * Sets {@code experimental}.
         *
         * @param experimental the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder experimental(FhirBoolean experimental) {
            this.experimental = experimental;
            return this;
        }

        /**
         * Sets {@code experimental}, wrapped in a {@link FhirBoolean} without id or extensions.
         *
         * @param experimental the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder experimental(Boolean experimental) {
            return experimental(experimental == null ? null : FhirBoolean.of(experimental));
        }

        /**
         * Sets {@code date}.
         *
         * @param date the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder date(FhirDateTime date) {
            this.date = date;
            return this;
        }

        /**
         * Sets {@code date}, wrapped in a {@link FhirDateTime} without id or extensions.
         *
         * @param date the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder date(Temporal date) {
            return date(date == null ? null : FhirDateTime.of(date));
        }

        /**
         * Sets {@code publisher}.
         *
         * @param publisher the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder publisher(FhirString publisher) {
            this.publisher = publisher;
            return this;
        }

        /**
         * Sets {@code publisher}, wrapped in a {@link FhirString} without id or extensions.
         *
         * @param publisher the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder publisher(String publisher) {
            return publisher(publisher == null ? null : FhirString.of(publisher));
        }

        /**
         * Replaces all {@code contact} values.
         *
         * @param contact the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder contact(List<ContactDetail> contact) {
            this.contact = contact == null ? new ArrayList<>() : new ArrayList<>(contact);
            return this;
        }

        /**
         * Adds a {@code contact} value.
         *
         * @param contact the value to add
         * @return this builder
         */
        public Builder addContact(ContactDetail contact) {
            this.contact.add(Objects.requireNonNull(contact, "contact"));
            return this;
        }

        /**
         * Sets {@code description}.
         *
         * @param description the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder description(FhirMarkdown description) {
            this.description = description;
            return this;
        }

        /**
         * Sets {@code description}, wrapped in a {@link FhirMarkdown} without id or extensions.
         *
         * @param description the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder description(String description) {
            return description(description == null ? null : FhirMarkdown.of(description));
        }

        /**
         * Replaces all {@code useContext} values.
         *
         * @param useContext the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder useContext(List<UsageContext> useContext) {
            this.useContext = useContext == null ? new ArrayList<>() : new ArrayList<>(useContext);
            return this;
        }

        /**
         * Adds a {@code useContext} value.
         *
         * @param useContext the value to add
         * @return this builder
         */
        public Builder addUseContext(UsageContext useContext) {
            this.useContext.add(Objects.requireNonNull(useContext, "useContext"));
            return this;
        }

        /**
         * Replaces all {@code jurisdiction} values.
         *
         * @param jurisdiction the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder jurisdiction(List<CodeableConcept> jurisdiction) {
            this.jurisdiction = jurisdiction == null ? new ArrayList<>() : new ArrayList<>(jurisdiction);
            return this;
        }

        /**
         * Adds a {@code jurisdiction} value.
         *
         * @param jurisdiction the value to add
         * @return this builder
         */
        public Builder addJurisdiction(CodeableConcept jurisdiction) {
            this.jurisdiction.add(Objects.requireNonNull(jurisdiction, "jurisdiction"));
            return this;
        }

        /**
         * Sets {@code purpose}.
         *
         * @param purpose the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder purpose(FhirMarkdown purpose) {
            this.purpose = purpose;
            return this;
        }

        /**
         * Sets {@code purpose}, wrapped in a {@link FhirMarkdown} without id or extensions.
         *
         * @param purpose the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder purpose(String purpose) {
            return purpose(purpose == null ? null : FhirMarkdown.of(purpose));
        }

        /**
         * Sets {@code copyright}.
         *
         * @param copyright the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder copyright(FhirMarkdown copyright) {
            this.copyright = copyright;
            return this;
        }

        /**
         * Sets {@code copyright}, wrapped in a {@link FhirMarkdown} without id or extensions.
         *
         * @param copyright the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder copyright(String copyright) {
            return copyright(copyright == null ? null : FhirMarkdown.of(copyright));
        }

        /**
         * Sets {@code copyrightLabel}.
         *
         * @param copyrightLabel the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder copyrightLabel(FhirString copyrightLabel) {
            this.copyrightLabel = copyrightLabel;
            return this;
        }

        /**
         * Sets {@code copyrightLabel}, wrapped in a {@link FhirString} without id or extensions.
         *
         * @param copyrightLabel the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder copyrightLabel(String copyrightLabel) {
            return copyrightLabel(copyrightLabel == null ? null : FhirString.of(copyrightLabel));
        }

        /**
         * Sets {@code approvalDate}.
         *
         * @param approvalDate the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder approvalDate(FhirDate approvalDate) {
            this.approvalDate = approvalDate;
            return this;
        }

        /**
         * Sets {@code approvalDate}, wrapped in a {@link FhirDate} without id or extensions.
         *
         * @param approvalDate the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder approvalDate(Temporal approvalDate) {
            return approvalDate(approvalDate == null ? null : FhirDate.of(approvalDate));
        }

        /**
         * Sets {@code lastReviewDate}.
         *
         * @param lastReviewDate the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder lastReviewDate(FhirDate lastReviewDate) {
            this.lastReviewDate = lastReviewDate;
            return this;
        }

        /**
         * Sets {@code lastReviewDate}, wrapped in a {@link FhirDate} without id or extensions.
         *
         * @param lastReviewDate the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder lastReviewDate(Temporal lastReviewDate) {
            return lastReviewDate(lastReviewDate == null ? null : FhirDate.of(lastReviewDate));
        }

        /**
         * Sets {@code effectivePeriod}.
         *
         * @param effectivePeriod the value, or {@code null} to clear it
         * @return this builder
         */
        public Builder effectivePeriod(Period effectivePeriod) {
            this.effectivePeriod = effectivePeriod;
            return this;
        }

        /**
         * Replaces all {@code resourceTrigger} values.
         *
         * @param resourceTrigger the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder resourceTrigger(List<ResourceTrigger> resourceTrigger) {
            this.resourceTrigger = resourceTrigger == null ? new ArrayList<>() : new ArrayList<>(resourceTrigger);
            return this;
        }

        /**
         * Adds a {@code resourceTrigger} value.
         *
         * @param resourceTrigger the value to add
         * @return this builder
         */
        public Builder addResourceTrigger(ResourceTrigger resourceTrigger) {
            this.resourceTrigger.add(Objects.requireNonNull(resourceTrigger, "resourceTrigger"));
            return this;
        }

        /**
         * Replaces all {@code eventTrigger} values.
         *
         * @param eventTrigger the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder eventTrigger(List<EventTrigger> eventTrigger) {
            this.eventTrigger = eventTrigger == null ? new ArrayList<>() : new ArrayList<>(eventTrigger);
            return this;
        }

        /**
         * Adds a {@code eventTrigger} value.
         *
         * @param eventTrigger the value to add
         * @return this builder
         */
        public Builder addEventTrigger(EventTrigger eventTrigger) {
            this.eventTrigger.add(Objects.requireNonNull(eventTrigger, "eventTrigger"));
            return this;
        }

        /**
         * Replaces all {@code canFilterBy} values.
         *
         * @param canFilterBy the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder canFilterBy(List<CanFilterBy> canFilterBy) {
            this.canFilterBy = canFilterBy == null ? new ArrayList<>() : new ArrayList<>(canFilterBy);
            return this;
        }

        /**
         * Adds a {@code canFilterBy} value.
         *
         * @param canFilterBy the value to add
         * @return this builder
         */
        public Builder addCanFilterBy(CanFilterBy canFilterBy) {
            this.canFilterBy.add(Objects.requireNonNull(canFilterBy, "canFilterBy"));
            return this;
        }

        /**
         * Replaces all {@code notificationShape} values.
         *
         * @param notificationShape the new values, or {@code null} to clear them
         * @return this builder
         */
        public Builder notificationShape(List<NotificationShape> notificationShape) {
            this.notificationShape = notificationShape == null
                    ? new ArrayList<>()
                    : new ArrayList<>(notificationShape);
            return this;
        }

        /**
         * Adds a {@code notificationShape} value.
         *
         * @param notificationShape the value to add
         * @return this builder
         */
        public Builder addNotificationShape(NotificationShape notificationShape) {
            this.notificationShape.add(Objects.requireNonNull(notificationShape, "notificationShape"));
            return this;
        }

        /**
         * Builds the {@code SubscriptionTopic}.
         *
         * @return the {@code SubscriptionTopic}
         * @throws NullPointerException if a required element is absent
         */
        public SubscriptionTopic build() {
            return new SubscriptionTopic(
                    id, meta, implicitRules, language, text, contained, extension, modifierExtension, url, identifier,
                    version, versionAlgorithm, name, title, derivedFrom, status, experimental, date, publisher,
                    contact, description, useContext, jurisdiction, purpose, copyright, copyrightLabel, approvalDate,
                    lastReviewDate, effectivePeriod, resourceTrigger, eventTrigger, canFilterBy, notificationShape);
        }
    }
}
